### ISSUE TITLE
Test get_os and get_package_manager functionality

### ISSUE THREAD

**Issue by thw26** [FaithLife-Community/LogosLinuxInstaller#1]
This is part of alpha testing. To get to beta, we need to verify the following.

- [x] `get_os()` properly detects the host's operating system
  - [x] Debian variants, `apt`
  - [x] RHEL variants, `dnf`
  - [x] RHEL variants, `yum` (this should be deprecated by now)
  - [x] Arch variants, `pacman`
  - [x] Arch variants, `pamac`
- [x] `get_package_manager()` properly detects the host's package manager
  - [x] `apt`
  - [x] `dnf`
  - [x] `yum`
  - [x] `pacman`
  - [x] `pamac`
- [x] verify the necessary packages for installation.
  - This requires a fresh ISO
  - [x] Logos 9 necessary packages.
    - Should we update the Logos 9 install routine or just use the Bash one? See #53.
  - [x] Debian. See #90.
  - [x] Ubuntu. See #90.
  - [x] Fedora
  - [x] CentOS (or another RHEL alternative)
  - [x] Arch. See #82.
  - [x] Manjaro. See #95.
  - [x] SteamOS. See #82.

The python rewrite reduces the number of dependencies in the application because we are now using python modules instead.

# Stretch Goals

- #16 
- #17 
- #14 
- #15 
- #26 
- #47 
- #48

**Comment by n8marti** [comment]
Let's make sure the relevant info from these functions is logged during install. Then we can more easily verify if they're working, and which systems have been tested.

**Comment by n8marti** [comment]
relevant logging output added in PR #40

**Comment by n8marti** [comment]
### Ubuntu

I can confirm that `get_os()` works correctly for Ubuntu by defining `config.OS_NAME` as`'ubuntu'` and `config.OS_RELEASE` as `'20.04'`. I don't know about debian, but I'd say it's safe to assume that all Ubuntu derivatives also at least have the `OS_RELEASE` value right.

`get_package_manager()` correctly sets `config.SUPERUSER_COMMAND` and correctly identifies `apt` as package manager. It looks like `config.PACKAGE_MANAGER_COMMAND_QUERY` also works, except that it finds all packages that start with the intended package name, not just the package itself. E.g. for Ubuntu and `binutils`:
```bash
$ dpkg -l | grep -E '^.i  'binutils
ii  binutils                                                    2.34-6ubuntu1.7                             amd64        GNU assembler, linker and binary utilities
ii  binutils-common:amd64                                       2.34-6ubuntu1.7                             amd64        Common files for the GNU assembler, linker and binary utilities
ii  binutils-x86-64-linux-gnu                                   2.34-6ubuntu1.7                             amd64        GNU binary utilities, for x86-64-linux-gnu target
```
In this case `binutils` is included in the results, so there's no problem. But it also matches `binutils-common:amd64` and `binutils-x86-64-linux-gnu`, which are maybe dependencies of `binutils`, but they are still additional results that turn up. But still, it's maybe unlikely that a "false positive" will be found without also finding the intended package in the same search.

**Comment by thw26** [comment]
From what I can tell, we can drop the following from Arch dependencies:

- curl
- gawk
- bc
- libxml2

Also, there is a duplicate of `patch` in the current list.

Manjaro's dependencies should be able to drop:

- curl
- gawk
- bc
- libxml2

RHEL should be able to drop:

- libxml2
- curl
- bc

It looks like `apt` is already set to be pretty bare, but we should probably add `grep`, `wget`, and `sed` to the requirements as these are used by the script.

These can be dropped because they were used in the Bash script but are no longer thanks to built-in Python libraries.

Also, does anyone remember why we need `samba`/`samba-winbind`? Was this something specific to Logos 9?

Further, cabextract (and samba?) should be able to be moved to L9PACKAGES, or removed if #53 is pursued.

One question this brings up: since our default/recommended Wine is an AppImage, should wine be a package in config.PACKAGES, as it is in Arch, or optional, as it is in Manjaro?

@jg00dman, is there any reason why wine-staging should definitely be a required packages instead of the appimage for steamOS?

**Comment by thw26** [comment]
Also, I think we will need to separate out the steamOS specific packages. I'm looking at things like qt5-virtualkeyboard and maybe some of the printing things or apparmor. Most of the libraries should be standard for just making sure we can call the proper libraries.

This will require a flag to switch these vars under the `elif…pacman` of `get_package_manager()` based on `config.OS_NAME`.

**Comment by thw26** [comment]
cabextract is needed in winetricks

patch is a Manjaro dependency for base-devel, fwiw
