### ISSUE TITLE
If Completed/Installed Config Exists but Logos EXE is Missing, Program Fails

### ISSUE THREAD

**Issue by thw26** [FaithLife-Community/LogosLinuxInstaller#138]
We need code to check if the config is valid, else the program breaks. Ideally we should notify the user if the config can't find the declared install and offer either to install or prompt for the user to check their config.

Make sure config paths are relative so that the install is self-contained and can be moved freely; that is, make sure the config doesn't break if someone moves their install from their initial install dir. cf. https://github.com/FaithLife-Community/LogosLinuxInstaller/issues/13.

**Comment by n8marti** [comment]
I ran into this while testing, and it's not clear what the precise conditions are to make this happen. In my testing I had a proper Logos Dir, etc., except that Logos itself wasn't installed within the wine prefix. The curses UI would just return to the initial screen when choosing either "Install Logos" or "Exit".

Removing the config file was the solution, but it doesn't seem to be related to bad config variables but rather something about the timing of when the config file is looked for when LLI runs. This needs more testing for sure.

**Comment by thw26** [comment]
Somehow this function is probably involved:

https://github.com/FaithLife-Community/LogosLinuxInstaller/blob/b472f4f85443e5ce64f05565df2cc8133c9a4fed/tui_app.py#L525
