### ISSUE TITLE
Fedora 40 - winetricks stuck on "corefonts", cannot progress

### ISSUE THREAD

**Issue by abbasou** [FaithLife-Community/LogosLinuxInstaller#162]
On Fedora 40 KDE. I want to say that I've had issues with `corefonts` in other attempts at winetricks for other projects (Affinity Designer, etc, I believe). Was able to manually install and proceed past that error. With LLI, the installer gets stuck and there is no way to proceed. Is it possible to skip `corefonts` during installation and manually copy the fonts after (or before)?

**Comment by abbasou** [comment]
So in peeking at config.py I noticed the SKIP_DEPENDENCIES and SKIP_FONTS flags. Went ahead and tried `SKIP_DEPENDENCIES=True SKIP_FONTS=True ./LogosLinuxInstaller` and lo and behold it installed without a fuss and seems to be running. I should note that I selected v29.1 since I read somewhere that v30+ had issues. Then again, maybe those were resolved with the icu*.dlls?

**Comment by thw26** [comment]
Logos 30+ is good to go!

**Comment by thw26** [comment]
You can also use flags `-K` and `-F` to skip deps and fonts respectively.

Is this issue able to be closed, or are you wanting us to investigate corefonts on Fedora more?

**Comment by abbasou** [comment]
Update again: Logos updated itself to the latest 36, so that seems to be working as well?

**Comment by abbasou** [comment]
> You can also use flags `-K` and `-F` to skip deps and fonts respectively.
> 
> Is this issue able to be closed, or are you wanting us to investigate corefonts on Fedora more?

Good to know! Is there any log dump or debug info I can provide that would help with the dependencies and corefonts issues? I'm not a developer and I'm not a linux poweruser, but I can mostly follow instructions and run commands if you guys want any more info.

**Comment by thw26** [comment]
If you want to get us a log dump, generally you can run the program with `-D` for debug mode, which should enable the wine logging.

**Comment by thw26** [comment]
I will close this issue. If you want to help further with Fedora deps, please see #143.
