### ISSUE TITLE
Synchronization does not work

### ISSUE THREAD

**Issue by apoxtin** [FaithLife-Community/LogosLinuxInstaller#169]
Hi! I am a noob at Linux and Github so forgive me if I am missing details or adding unnecessary details.

I just installed Logos using the TUI on Nobara 40, a Fedora based distro. The install went well after I skipped checking dependencies and fonts. Before that it got stuck in the installation process. 

The app seems to be working fine for the most part. I can download resources in the Library and most functions seem to be working so far. But I am having an issue where synchronization in Logos does not work. The little icon in the left-hand corner says on hover "An error occured during synchronization, click to try again". But clicking it again doesn't change anything. 

Also, it cannot load any of my notes and when I try to create a new note the app crashes. I've tried this with the three most recent Logos versions (36.1, 36, 35) but it doesn't seem to make a difference. The sync still does not work.

Here is a pastebin to the log from where the app crashed when attempting to open notes:
https://pastebin.com/dXT0A0Gp

**Comment by thw26** [comment]
Thank you for reporting this. In order for us to debug this, we would need to have the wine debug logs. You can get those by running the application with the `-D` flag.

This is not going to be our bug, as we have no control over how Logos interacts with Wine directly. This is going to be an upstream bug with Wine and its support for however Logos initiates its syncing.

That being said, we are working on some code that would let us synchronize our books, but I have not seen the Notes issue before. I recently witnessed Logos perform an update, which has been broken for a long time on our end.

**Comment by thw26** [comment]
Latest testing suggests newer wine versions have resolved this (9.16+). Please reopen if this continues to be an issue.
