### ISSUE TITLE
Program Icon Appears as a Gear on GNOME Desktop Bar

### ISSUE THREAD

**Issue by thw26** [FaithLife-Community/LogosLinuxInstaller#171]

**Comment by jimbob88** [comment]
I am not getting this issue on Debian GNU/Linux 12 (bookworm), Gnome 43.9, X11 [verbum + logos 10]:

![image](https://github.com/user-attachments/assets/4d70bfbd-1d9a-4a2e-b0f9-df1822ecd363)

Using build on https://github.com/FaithLife-Community/LogosLinuxInstaller/commit/f02e0133670040337b0351de7582034f827e10ba

**Comment by n8marti** [comment]
This definitely happens if Logos is installed using the script because there's no associated `.desktop` file. But I'm not seeing this either after installing using the binary. @thw26 can you reproduce this after installing via the binary?

**Comment by thw26** [comment]
Is this the launcher's icon or our program's icon?

I'll need time to set up a dev environment, as all my dev environments run Plasma.
