### ISSUE TITLE
ChromeOS Compositor Issues

### ISSUE THREAD

**Issue by thw26** [FaithLife-Community/LogosLinuxInstaller#25]
Our main ChromeOS user has reported that ChromeOS's containerization works with Logos, but it draws black bockes (i.e., compositor issues). Is this solely on ChromeOS's side? Is there anything we need to do or can do on our side?

**Comment by benmordecai** [comment]
Does this happen with all Wine applications?

**Comment by waa1523** [comment]
This issue has been resolved, finally! The fix is for ChromeOS users to open their Chrome browser, type chrome//flags in the search box and search for Crostini GPU support. The fix is changing the value from Default to Disabled.
