### ISSUE TITLE
Downloaded binary is not executable

### ISSUE THREAD

**Issue by n8marti** [FaithLife-Community/LogosLinuxInstaller#30]
If you download the "LogosLinuxInstaller" binary from the "Releases" page it will not be executable. The user has to either `chmod +x LogosLinuxInstaller` or use the file manager context menu to make it executable.

It looks like there are only 2 possibilities:
1. Keep it as-is, inform users how to make it executable after downloading.
2. Release it as a .tar.gz file, which will retain the file permissions but then require the user to extract it after download.
References:
- explanation of the principle: https://stackoverflow.com/a/77319717
- example of repo using choice 2: https://github.com/iamazeem/spancopy/releases

**Comment by thw26** [comment]
This is just good security. Let's keep it without tar.gz so we don't need to explain unarchiving and uncompressing and just teach folks how to `chmod 700`.

Agreed?

Alternatively, how much disk space in a download can be saved by compression? This could help our limited bandwidth folks.

**Comment by n8marti** [comment]
The size reduction is minimal when tested locally:
```
$ stat -c%s LogosLinuxInstaller
29398656
$ tar -ckzf LogosLinuxInstaller.tar.gz LogosLinuxInstaller
$ stat -c%s LogosLinuxInstaller.tar.gz 
29100308
```
This isn't surprizing, because PyInstaller itself uses compression when creating the binary. Although it could be possible to tweak PyInstaller's build settings to use higher compression. All in all, I'm in a low/expensive bandwidth situation, and I wouldn't be too worried about 29 MB. That's less than most Android app updates.

**Comment by n8marti** [comment]
Back to the original question, I agree that teaching users to make the file executable is a good solution. Closing the Issue.
