### ISSUE TITLE
Cannot Detect If On Devel Branch

### ISSUE THREAD

**Issue by thw26** [FaithLife-Community/LogosLinuxInstaller#32]
@n8marti and I discussed this issue and we do not see a good solution. Beginning with 8.16+ (IIRC) we no longer need to use staging but can use devel. Unfortunately, our method for detecting the branch used can distinguish between staging and stable but not between devel and stable, or put another way, our current check can determine if we are using staging or if stable/devel.

What this means is that the script errors on a valid wine devel version, not presenting it as an option for install. Meaning we are effectively back to using staging.

At present, the only option would be to detect the branch based on an operating system specific check, which we have available with the `get_os()` implemented in the rewrite, but this feels like overkill.

**Comment by n8marti** [comment]
some breadcrumbs to follow:
- winehq packages for ubuntu install wine to `/opt/wine-{$branch}/`
- The current appimage for 8.19 does the same, which you can see _if_ you:
  - mount the image with `wine-${blahblahblah}.appimage --appimage-mount`
  - note the mount path in the terminal output
  - open another terminal to this path and do `ls ${mount_path}/opt/`, and you will see either `wine-staging`, `wine-devel`, or `wine-stable` in that folder

AppImages also have a command to extract certain files. Maybe this could be used to sniff out the wine branch used without having to mount the AppImage. For example, I've found that it can be discovered inside mscoree.dll:
```
$ grep -aEo 'wine-[a-z]+' /opt/wine-stable/lib/wine/i386-windows/mscoree.dll 
wine-stable
```

**Comment by thw26** [comment]
Searching a DLL might work, as that should be available on all systems if we search the right directory. We would need to pair the wine binary candidate with the dir containing its DLLs and then we should be able to search whatever we want. It might even be faster than waiting on a `wine --version` check since we don't need to wait for the heavy wine bin to load.

We might then be able to simplify the whole thing even, as then we could determine the binary's branch with a simple sed or awk.

**Comment by n8marti** [comment]
It would need some verification, but I bet the relative paths from the wine
binary to the mscoree.dlls are always the same, provided you resolve the
symlink at `/bin/wine` or `/usr/bin/wine` first that you'll probably find
on system installs.

**Comment by n8marti** [comment]
I've started working on this in [issue32 branch](https://github.com/FaithLife-Community/LogosLinuxInstaller/tree/issue32). It detects but doesn't yet handle AppImages, though.
