### ISSUE TITLE
Linux Mint installation failed with Proton and v30 also fails with appimage

### ISSUE THREAD

**Issue by joshuabeny1999** [FaithLife-Community/LogosLinuxInstaller#39]
Hello

I tried to install Logos with the older Skript from the old repo which failed completely. The Logos installer says windows needs to be updated. I then tried tmanuall ylink the prodon dir but it then only found win64 and not winserver. 

So i tried now the alpha:

To thet the python script working i aditianlly needed next to install the requirements.txt: 
- sudo apt install python3-tk 
- pip3 install distro

I then tried to Install using proton by also passing the custom path (On my machine i installed steam via the app store provided by Linux mint and htere the steamapps and also Proton Folder seems to be different than the default one). This failed with following error:
```
./LogosLinuxInstaller.py --custom-binary-path /home/joshua/.steam/debian-installation/steamapps/common/Proton\ 8.0/dist/bin
Installer log file: /home/joshua/.local/state/Logos_on_Linux/install.log
                                                                        Logos Linux Installer, 4.0.0-alpha.1 by Ferion11, John Goodman, T. H. Wright, N. Marti.
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
                                                                           Downloading release list for Logos 10...
Traceback (most recent call last):
                                    File "/home/joshua/Dokumente/git/LogosLinuxInstaller/wine.py", line 128, in wineBinaryVersionCheck
                                                                                                                                          version, release = version_string.split()
       ValueError: not enough values to unpack (expected 2, got 1)

                                                                  During handling of the above exception, another exception occurred:

                                                                                                                                     Traceback (most recent call last):
                                                                                                                                                                         File "/home/joshua/Dokumente/git/LogosLinuxInstaller/./LogosLinuxInstaller.py", line 254, in <module>
                                                                                                      main()
                                                                                                              File "/home/joshua/Dokumente/git/LogosLinuxInstaller/./LogosLinuxInstaller.py", line 221, in main
                                       install()
                                                  File "/home/joshua/Dokumente/git/LogosLinuxInstaller/installer.py", line 453, in install
                                                                                                                                              prepare_install()
                                                                                                                                                                 File "/home/joshua/Dokumente/git/LogosLinuxInstaller/installer.py", line 461, in prepare_install
                                                                                         chooseInstallMethod()  # We ask user for his desired install method.
                                                                                                                                                               File "/home/joshua/Dokumente/git/LogosLinuxInstaller/installer.py", line 172, in chooseInstallMethod
                                                                                           binaries = createWineBinaryList()
                                                                                                                              File "/home/joshua/Dokumente/git/LogosLinuxInstaller/wine.py", line 90, in createWineBinaryList
                                                     output1, output2 = wineBinaryVersionCheck(binary)
                                                                                                        File "/home/joshua/Dokumente/git/LogosLinuxInstaller/wine.py", line 131, in wineBinaryVersionCheck
                                  release = get_wine_branch(TESTBINARY)
                                                                         File "/home/joshua/Dokumente/git/LogosLinuxInstaller/wine.py", line 326, in get_wine_branch
                                                                                                                                                                        appimage, appimage_type = is_appimage(binary_obj)
                                               File "/home/joshua/Dokumente/git/LogosLinuxInstaller/utils.py", line 856, in is_appimage
                                                                                                                                           return (elf_sig == b'ELF' and ai_sig == b'AI', int.from_bytes(v_sig))
                                    TypeError: from_bytes() missing required argument 'byteorder' (pos 2)
```

This error i tried to fix manually, by adjusting the line to following: 
```python
    return (elf_sig == b'ELF' and ai_sig == b'AI', int.from_bytes(v_sig, byteorder='little'))
 ```
 Then i got following error (It seems not to get version correctly:
 ```
 ./LogosLinuxInstaller.py -p ~/.steam/debian-installation/steamapps/common/Proton*/dist/bin
Installer log file: /home/joshua/.local/state/Logos_on_Linux/install.log
                                                                        Logos Linux Installer, 4.0.0-alpha.1 by Ferion11, John Goodman, T. H. Wright, N. Marti.
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
                                                                           Downloading release list for Logos 10...
/home/joshua/.steam/debian-installation/steamapps/common/Proton 8.0/dist/bin/wine64has binary
                                                                                             Traceback (most recent call last):
                                                                                                                                 File "/home/joshua/Dokumente/git/LogosLinuxInstaller/./LogosLinuxInstaller.py", line 254, in <module>
                                                              main()
                                                                      File "/home/joshua/Dokumente/git/LogosLinuxInstaller/./LogosLinuxInstaller.py", line 221, in main
                                                                                                                                                                           install()
          File "/home/joshua/Dokumente/git/LogosLinuxInstaller/installer.py", line 453, in install
                                                                                                      prepare_install()
                                                                                                                         File "/home/joshua/Dokumente/git/LogosLinuxInstaller/installer.py", line 461, in prepare_install
                                                 chooseInstallMethod()  # We ask user for his desired install method.
                                                                                                                       File "/home/joshua/Dokumente/git/LogosLinuxInstaller/installer.py", line 172, in chooseInstallMethod
                                                   binaries = createWineBinaryList()
                                                                                      File "/home/joshua/Dokumente/git/LogosLinuxInstaller/wine.py", line 92, in createWineBinaryList
             output1, output2 = wineBinaryVersionCheck(binary)
                                                                File "/home/joshua/Dokumente/git/LogosLinuxInstaller/wine.py", line 137, in wineBinaryVersionCheck
                                                                                                                                                                      release = release.lstrip('(').rstrip(')').lower() # remove parentheses
                                                                AttributeError: 'NoneType' object has no attribute 'lstrip'

 ```
 
 I then tried the appImage version of the installation. THe latest v30.0 Version seems to have failed:
 ![image](https://github.com/FaithLife-Community/LogosLinuxInstaller/assets/55023662/86cdb1b2-e6b9-4d42-9398-e705643d1860)

v29 i could install. 

But i have two questions: 
- How to set scaling. It seems to small to be readable at all. Like the installation screen on screenshot above it is really small. 
- Is it possible to have a desktop shortcut?

**Comment by joshuabeny1999** [comment]
The scaling issue i could resolve. Logos offers to set the scaling over the three dots menu on bottom left. 

But performance is not the best. I guess proton would be better, due i can game also with it so i would love to get it working wiht proton.

**Comment by thw26** [comment]
>I tried to install Logos with the older Skript from the old repo which failed completely. The Logos installer says windows needs to be updated. I then tried tmanuall ylink the prodon dir but it then only found win64 and not winserver.

This is #22.

You should be able to get a desktop shortcut by running the app and either selecting the shortcut creation button or running the binary with the `-s` option.

@n8marti, any thoughts on the other issue?

**Comment by n8marti** [comment]
A couple of thoughts:
- I wish I knew why, but somehow the terminal wrapping goes haywire if there's an exception while running the terminal-based script.
- The script is written in Python 3.12, and that byteorder parameter was given a default setting as 'big' in 3.11. So you're using a python version <3.11, which is probably why you got the `TypeError` in the first run you show.
- Regarding the `NoneType` error for `release = release.lstrip()`, it's hard to sort out because you're running the script from our `main` branch, which is changing frequently right now. But I think it's failing on the `wine.get_mscoree_winebranch` function. If you have it, can you upload the log file at `~/.local/state/Logos_on_Linux/install.log`? That might give us some more useful debugging details.
- Is it possible that your Proton installation is only 32-bit? The function mentioned above looks specifically for the 64-bit `mscoree.dll` file among the wine libraries.
- Lastly, you're probably better off downloading and running binary on the [Releases page](https://github.com/FaithLife-Community/LogosLinuxInstaller/releases), because it includes all the dependencies already. Or, if you really want to run the script, switch to the `v4.0.0-alpha.1` tag in the "branches" menu so that we know for certain which version of the script you're running.
- If you do run the script, you would be better off creating a virtual environment, ensuring that Python 3.12 is installed in it, then running `pip install -r requirements.txt`. To ensure the best outcome. I have a lightly-tested explanation of this in the `scripts` folder of the branch `altdev`, which is not yet merged in.

**Comment by n8marti** [comment]
By "explanation" in the last bullet point above, I mean "two scripts that install Python 3.12 and set up the virtual environment on an Ubuntu-based system". I think your Mint installation *should* be compatible...

**Comment by joshuabeny1999** [comment]
Here is the log. Its pretty long. I guessing some log entries where from the bash skript. 
[install.log](https://github.com/FaithLife-Community/LogosLinuxInstaller/files/13861721/install.log)
 

I was using python 3.10 and not 3.12 which was preinstalled from the distro. I already created the venv and did it with the main branch but there wasn't mentioned the version. 

But i rather try the binary first if it works. This is the output of the ls -a command. So proton is surely installed with 64-bit:
```sh
ls -la ~/.steam/debian-installation/steamapps/common/Proton*/dist/bin
insgesamt 768
drwxr-xr-x 2 joshua joshua   4096 Okt 19 12:46 .
drwxr-xr-x 6 joshua joshua   4096 Dez 27 01:23 ..
-rwxr-xr-x 1 joshua joshua   2101 Okt 19 12:46 msidb
-rwxr-xr-x 1 joshua joshua  15560 Okt 19 12:46 wine
-rwxr-xr-x 1 joshua joshua  16712 Okt 19 12:46 wine64
-rwxr-xr-x 1 joshua joshua  18488 Okt 19 12:46 wine64-preloader
-rwxr-xr-x 1 joshua joshua  17664 Okt 19 12:46 wine-preloader
-rwxr-xr-x 1 joshua joshua 695040 Okt 19 12:46 wineserver
```

**Comment by joshuabeny1999** [comment]
Hmm the binary seems not to find the wine binary if i passing the custom folder to the script:
![image](https://github.com/FaithLife-Community/LogosLinuxInstaller/assets/55023662/6777b67c-9520-42c1-a329-3ca7286666fc)
It provides only the option using the AppImage and not my Proton installation by passing the custom path. 

The binary provides me with an better error message:
```sh
2024-01-08 15:23:16 INFO: Removing binary: /home/joshua/.steam/debian-installation/steamapps/common/Proton 8.0/dist/bin/wine64 because: Can't use Stable release
2024-01-08 15:23:21 DEBUG: config.FLPRODUCT: Logos
2024-01-08 15:23:21 DEBUG: config.FLPRODUCTi: logos4
2024-01-08 15:23:21 DEBUG: config.LOGOS_VERSION: 29.1.0.0022
2024-01-08 15:23:21 DEBUG: config.INSTALLDIR: /home/joshua/LogosBible10
2024-01-08 15:23:21 DEBUG: config.APPDIR: /home/joshua/LogosBible10/data
2024-01-08 15:23:21 DEBUG: config.APPDIR_BINDIR: /home/joshua/LogosBible10/data/bin
2024-01-08 15:23:21 INFO: Removing binary: /home/joshua/.steam/debian-installation/steamapps/common/Proton 8.0/dist/bin/wine64 because: Can't use Stable release
```
Would be nice to show such error in the GUI. 

So is only proton experminental supported yet?

I will try to change the steam settings to use experimental version instead of 8.0 and try again. 

But congratulation, the binary is much more convient.

**Comment by thw26** [comment]
Proton 7.0 is supported. Wine 8.0 is broken, and thus Proton 8.0 is broken.

**Comment by joshuabeny1999** [comment]
Yeah Proton Experimental seemed also not to work... 

Says also Can't use Stable release. Will you fix it at a lather date? So it rather recommended to stay with the Appimage Version? Proton 7 is pretty old. Or is the Performance better with Proton 7?

**Comment by thw26** [comment]
>Says also Can't use Stable release. Will you fix it at a lather date?

This is an issue with Wine. With Wine 8.16+, we can use devel instead of staging.

>So it rather recommended to stay with the Appimage Version?

This is our method for a stable(ish) install.

>Proton 7 is pretty old. Or is the Performance better with Proton 7?

I agree. I've wanted to test Proton GE builds but haven't had time. If you have time to test, I encourage you to do so! I'd love to be able to test the latest Valve improvements for our use case.

**Comment by joshuabeny1999** [comment]
How to i get Proton GE? Steam itselfs does not have that option. 

I think i leave it with the current installation which seems  have work also with 3.10 python and appimage. 

But creation of the shortcut seems not working. I ran the python script with the option --shortcut in the terminal but it opens the script with the pages to choose run logos, run indexing, etc. And does not create anything. This is really a hussle to always need to change to the folder, launch the virtual env and then start the app. Due the binary i downloaded does not provide an option at all to launch it due it seems not to reconise the existing installation.

**Comment by joshuabeny1999** [comment]
Also i had a strange error: I tried to ran the binary in GUI mode (double clicking) and then install. In the log it has correctly an critical error that the Installation already exists. But i got logged out entireley as the whole login broke. Maybe another issue that need to be checked.

**Comment by n8marti** [comment]
I think in the next few days we'll be releasing `v4.0.0-alpha.2` (right, @thw26?), which brings in a lot of fixes. I would suggest waiting for that before doing any testing. Otherwise, using the alpha.1 release and the AppImage with Logos v29 should work best if you have to reinstall again right away.

**Comment by joshuabeny1999** [comment]
Currently i have a working installation i only want to have a shortcut to simplyfiy opening the App ;)

Do not want to reinstall everything and redownload my libary which is about 5GB. But can't wait for upcoming fixes, especially version 30. Hopefully it will be possible to upgrade instead of reinstall. Or at least be a way to transfer the library over to the new installation.

**Comment by joshuabeny1999** [comment]
Hmm it seems to have created a shortcut without any icon in .local/share/applications/Logos with command `wine C:/users/joshua/AppData/Local/Logos/System/Logos.exe` but that seems not been working. Timing is last night when app was installed last night.

**Comment by n8marti** [comment]
The easiest solution is probably to edit that file so that it has the correct info for your working installation. Can you upload it?

**Comment by n8marti** [comment]
You'll probably have the icon file in your Downloads folder as `logos4-128-icon.png`. And you'll want to make sure the Exec line is correct

**Comment by joshuabeny1999** [comment]
Yes what would be the correct exec line. As reverse engineering it seems to run following two commands if i choose Run Logos:
``sh
/home/joshua/LogosBible10/data/bin/wineserver None -w
/home/joshua/LogosBible10/data/bin/wine64 /home/joshua/LogosBible10/data/wine64_bottle/drive_c/users/joshua/AppData/Local/Logos/Logos.exe
```
If i try to chain it in the exec as following i see the startup sceen but not the app itself. What does the python script do differently?: 
/home/joshua/LogosBible10/data/bin/wineserver None -w  & /home/joshua/LogosBible10/data/bin/wine64 /home/joshua/LogosBible10/data/wine64_bottle/drive_c/users/joshua/AppData/Local/Logos/Logos.exe

**Comment by joshuabeny1999** [comment]
[Logos.cinnamon-generated.desktop.tar.gz](https://github.com/FaithLife-Community/LogosLinuxInstaller/files/13863265/Logos.cinnamon-generated.desktop.tar.gz)

**Comment by n8marti** [comment]
The packaged *binary*, which includes the script and all its dependencies, sets the correct environment variables before launching the app. So your `Exec` line needs to reference the script or binary. So we first need to determine which one of those to use and where it is. Can you tell me what's in `$HOME/LogosBible10` with:
```
$ find ~/LogosBible10 -maxdepth 3
```

**Comment by joshuabeny1999** [comment]
```sh
/home/joshua/LogosBible10
/home/joshua/LogosBible10/data
/home/joshua/LogosBible10/data/Logos_v29.1.0.0022-x64.msi
/home/joshua/LogosBible10/data/bin
/home/joshua/LogosBible10/data/bin/wine64
/home/joshua/LogosBible10/data/bin/selected_wine.AppImage
/home/joshua/LogosBible10/data/bin/wineserver
/home/joshua/LogosBible10/data/bin/wine
/home/joshua/LogosBible10/data/bin/winetricks
/home/joshua/LogosBible10/data/bin/wine-devel_8.19-x86_64.AppImage
/home/joshua/LogosBible10/data/wine64_bottle
/home/joshua/LogosBible10/data/wine64_bottle/user.reg
/home/joshua/LogosBible10/data/wine64_bottle/userdef.reg
/home/joshua/LogosBible10/data/wine64_bottle/system.reg
/home/joshua/LogosBible10/data/wine64_bottle/dosdevices
/home/joshua/LogosBible10/data/wine64_bottle/.update-timestamp
/home/joshua/LogosBible10/data/wine64_bottle/drive_c
/home/joshua/LogosBible10/data/wine64_bottle/winetricks.log
```

Here the output.

**Comment by n8marti** [comment]
Thanks. And can you tell me if your working installation was done with the binary or with the script? If you're not sure, you could try to find both with:
```
$ find ~ -name 'LogosLinuxInstaller*'
```

**Comment by joshuabeny1999** [comment]
I downloaded the repo there:
```sh
/home/joshua/Dokumente/git/LogosLinuxInstaller
/home/joshua/Dokumente/git/LogosLinuxInstaller/LogosLinuxInstaller.spec
/home/joshua/Dokumente/git/LogosLinuxInstaller/LogosLinuxInstaller.py
```

**Comment by n8marti** [comment]
try this desktop file by putting it in `~/.local/share/applications` and removing the '.txt' from the end of the name.
[Logos-v4.0.0-alpha.1-joshua.desktop.txt](https://github.com/FaithLife-Community/LogosLinuxInstaller/files/13863536/Logos-v4.0.0-alpha.1-joshua.desktop.txt)

**Comment by n8marti** [comment]
If "Logos" shows up twice in your app menu, this will has the Comment line "Logos (4.0.0-alpha.1 hack)".

**Comment by joshuabeny1999** [comment]
Thank you for the updated file. it seems not working properly, I tnot open anything and if i runn the command in terminal i get followign error:
```sh
/home/joshua/LogosBible10/data/wine64_bottle/drive_c/users/joshua/AppData/Local/Logos/Logos.exe: 1: MZ����@���: not found
/home/joshua/LogosBible10/data/wine64_bottle/drive_c/users/joshua/AppData/Local/Logos/Logos.exe: 1: Syntax error: Unterminated quoted string
```

For debugging purpose. Here my config file which i can open with edit config:
```json
{
    "APPDIR": "/home/joshua/LogosBible10/data",
    "APPDIR_BINDIR": "/home/joshua/LogosBible10/data/bin",
    "APPIMAGE_LINK_SELECTION_NAME": "selected_wine.AppImage",
    "BACKUPDIR": null,
    "FLPRODUCT": "Logos",
    "FLPRODUCTi": "logos4",
    "INSTALLDIR": "/home/joshua/LogosBible10",
    "LOGOS_DIR": null,
    "LOGOS_EXE": "/home/joshua/LogosBible10/data/wine64_bottle/drive_c/users/joshua/AppData/Local/Logos/Logos.exe",
    "LOGOS_EXECUTABLE": "Logos_v29.1.0.0022-x64.msi",
    "LOGS": null,
    "TARGETVERSION": "10",
    "WINE64_APPIMAGE_FULL_FILENAME": "wine-devel_8.19-x86_64.AppImage",
    "WINE64_APPIMAGE_FULL_URL": "https://github.com/FaithLife-Community/LogosLinuxInstaller/releases/download/wine-devel-8.19/wine-devel_8.19-x86_64.AppImage",
    "WINEBIN_CODE": "AppImage",
    "WINECMD_ENCODING": "850",
    "WINEPREFIX": "/home/joshua/LogosBible10/data/wine64_bottle",
    "WINESERVER_EXE": "/home/joshua/LogosBible10/data/bin/wineserver",
    "WINETRICKSBIN": "/home/joshua/LogosBible10/data/bin/winetricks",
    "WINE_EXE": "/home/joshua/LogosBible10/data/bin/wine64"
}
```

**Comment by n8marti** [comment]
https://matrix-client.matrix.org/_matrix/media/v3/download/t2bot.io/f21a1ecf8da08c60a15e67923dda742a1a55729d1742123923635437568

In Logos' settings there's an option to turn off "Automatically start downloads" (yours might be in German?). This will prevent automatic app updates from downloading, as well as resource updates. But I think you can go to individual resources in the Library and download them one at a time. I'm not so sure about resource updates, though.

**Comment by n8marti** [comment]
> You should be able to get a desktop shortcut by running the app and either selecting the shortcut creation button or running the binary with the `-s` option.

@thw26 The `--shortcut` option exists in `v4.0.0-alpha`, but I don't think it was actually implemented yet. It will be when #40 is merged, though, so I assume that it will be included in `v4.0.0-alpha.2`

**Comment by joshuabeny1999** [comment]
Thank you found the option. Yeah the tooltip mentions that also resources won't be updated. But there is another option download new books which says it will download new books automatically. So i will see. 

Thank you again for your time and support. Glad i have now a working Logos installation on my Linux client. Feel free to close this issue and open seperate ones for keep track of other things. And if you need to test further things, don^t hesitate to write. I am open to test again later maybe the upgrade from v29 to v30 if you have fixed it.

**Comment by n8marti** [comment]
You're welcome. We hope to have backup and restore options built in by `beta`. That would presumably be how you could upgrade in the future without having to redownload all your resources (or you could always manually copy the relevant folders elsewhere before upgrading, then move them back afterwards, if you're industrious to find out or ask where they are). And at that point it will install proper `.desktop` files, as well, and you'll be able to delete the workaround.
