### ISSUE TITLE
Running the install action crashes kde on kubuntu

### ISSUE THREAD

**Issue by jg00dman** [FaithLife-Community/LogosLinuxInstaller#68]
If the installer is run by double clicking then once you select to install it crashes the whole desktop session.

**Comment by thw26** [comment]
Do you get anything in the logs? ~/.local/state/Logos_on_Linux/Logos_on_Linux.log

**Comment by thw26** [comment]
Just ran a test and it did not crash here on Manjaro KDE through double click.

**Comment by maybeageek** [comment]
While it does not crash immediatly when I install, it does not finish. Running the installer again will then crash KDE for me. (Arch KDE 5 and 6, I updated inbetween)

**Comment by thw26** [comment]
>While it does not crash immediatly when I install, it does not finish. Running the installer again will then crash KDE for me. (Arch KDE 5 and 6, I updated inbetween)

If there were two instances of the installer running, this could have crashed the desktop. We normally have a safeguard in place to prevent running two instances of the installer, but I recall having to disable it not that long ago for some reason. This could be a secondary crash unrelated to the one reported in this issue.

**Comment by thw26** [comment]
>While it does not crash immediatly when I install, it does not finish. Running the installer again will then crash KDE for me. (Arch KDE 5 and 6, I updated inbetween)

If there were two instances of the installer running, this could have crashed the desktop. We normally have a safeguard in place to prevent running two instances of the installer, but I recall having to disable it not that long ago for some reason. This could be a secondary crash unrelated to the one reported in this issue.

See this FIXME:

https://github.com/FaithLife-Community/LogosLinuxInstaller/blob/6f8d420a4946defd292cc067f756f25a6c886995/LogosLinuxInstaller.py#L309C1-L311

**Comment by thw26** [comment]
John now says it is not crashing. We will need further testing to confirm, but this might be able to be closed with no specific PR.

**Comment by jg00dman** [comment]
Yep, works for me...
