### ISSUE TITLE
Logos Itself Throws Error When Updating

### ISSUE THREAD

**Issue by thw26** [FaithLife-Community/LogosLinuxInstaller#74]
We've had two reports of successful installations which throw an error after attempting to update the program or resources.

**Comment by c-reeder** [comment]
I am not sure if there are two issues here, but the one that I've run into is not at installation time (and thus I don't yet see a connection with the scripts in this repo).
The installation completes successfully, but from that point onwards, each time the application starts, it tries to update the application (currently on `29.1.22`) automatically and it fails.

1. First the message that it is downloading the update.
![2024-03-06_10-12](https://github.com/FaithLife-Community/LogosLinuxInstaller/assets/5522957/6dc31f95-5703-4207-9f41-ef005b0e5e46)

2. Then when it completes the download, it throws this error dialog:
![2024-03-06_09-56](https://github.com/FaithLife-Community/LogosLinuxInstaller/assets/5522957/fa8b9ede-34a9-4555-9808-cfdce45536e8)

3. After dismissing that error dialog, the application continues to run and perform correctly it seems. However, you can see that the application update is in a stuck state in the logos notification tray.
![2024-03-06_10-08](https://github.com/FaithLife-Community/LogosLinuxInstaller/assets/5522957/4b128ecd-c6cf-47e6-b8c6-18efc7e13a85)

Each time the app opens, it retries this (downloads that whole 300 MB and then throws the error) and then is usable as usual.

**Comment by thw26** [comment]
Ah, this is a different issue, yes, than the one reported previously.

**Comment by c-reeder** [comment]
Was that the one reported by Anthony?

> Thanks again, installed, downloaded, and indexed fine.  restarted linux and works good, except every time i run it i get an error: logos setup: the installation of Logos Bible Study did not succeed. (i think It is a wine error- the taskbar shows the error with the "wine" icon).  can i just ignore this?

That looks like it may be the same one, but just misidentified?

**Comment by thw26** [comment]
That's the one!

Okay, so we have a new issue with automatic updates, correct? But it is not corrupting your install, right?

**Comment by thw26** [comment]
My best guess is that this is a duplicate of #22, unless you have reason to think otherwise.

**Comment by c-reeder** [comment]
I think it's totally possible that it's the same underlying issue manifesting in these two ways, but I'm not familiar enough with this yet to make a statement there.

**Comment by thw26** [comment]
Closing as duplicate of #22. If we can find evidence of something else, let's reopen.
