### ISSUE TITLE
Gzip'd Response causes Failed File Size Check

### ISSUE THREAD

**Issue by savionlee** [FaithLife-Community/LogosLinuxInstaller#9]
## Expected Behavior

File Size check should deflate the url response to compute size if `content-encoding: gzip` is in the headers

## Current Behavior

File size is taken from the `content-length`. Since the file on the server was sent as compressed, it is smaller than the file to be checked.

## Possible Solution

The file downloads to the correct size, so maybe it gets downloaded with a temporary extension, after it completes, we check the file size of the temporary. Afterwards, remove the temporary extension before the md5 check.

Alternatively, I found this stackexchange that says to deflate and then do what you want. https://stackoverflow.com/questions/20537432/force-webserver-to-return-uncompressed-data-no-gzip

## Steps to Reproduce

1. fresh install
2. download 10, use wine app image
3. wait till it gets to wine tricks
4. see error

## Context (Environment)

Fedora 39, GNOME Wayland

## Detailed Description

On a fresh install, the installer fails with error
```
2023-12-28 16:05:42 CRITICAL: Bad file size or checksum: /home/user1/Downloads/winetricks
```
In debug log, it shows a smaller url_size than after the size of the file downloaded:
```
2023-12-28 15:39:46 DEBUG: url_size = 191443 B; file_size = 904682 B
```
Examining the headers in firefox, github is responding with a gzip compression, so this line is returning a compressed value to be judged by the same_file size

Headers to the raw file:
```
HTTP/2 200 
content-encoding: gzip
content-length: 191443
cache-control: max-age=300
content-security-policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
content-type: text/plain; charset=utf-8
etag: W/"6ea1078523c73e321b37fc6db2781620d63401e3320f9033c20d9b6d4fcc0c48"
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 1; mode=block
x-github-request-id: D7C2:63A2:3A603F:47A7B1:658DEB1C
accept-ranges: bytes
date: Thu, 28 Dec 2023 22:58:02 GMT
via: 1.1 varnish
x-served-by: cache-dfw-kdfw8210092-DFW
x-cache: HIT
x-cache-hits: 1
x-timer: S1703804282.138054,VS0,VE105
vary: Authorization,Accept-Encoding,Origin
access-control-allow-origin: *
cross-origin-resource-policy: cross-origin
x-fastly-request-id: 1fb49f40c6dfdaa7a8f773e397fb219cd5dd68f6
expires: Thu, 28 Dec 2023 23:03:02 GMT
source-age: 0
X-Firefox-Spdy: h2
```

[LogosLinuxInstaller/utils.py Line 92](https://github.com/FaithLife-Community/LogosLinuxInstaller/blob/cc55082b8a8e2b312f78e539b521e158308b7f18/utils.py#L92C39-L92C39)
```
        content_length = self.headers.get('Content-Length')
```

**Comment by godfollower** [comment]
Also present using Debian 12 with a clean install/appimage selected

**Comment by n8marti** [comment]
Thanks for the clear problem description and helpful link, @savionlee. I have posted the above commit, [085d119](https://github.com/FaithLife-Community/LogosLinuxInstaller/commit/085d1194ffd483c424c6d875cf0361d29671a0d9), in a branch, but this needs testing in a clean system. I may have time later today, but not at the moment.

**Comment by n8marti** [comment]
Here's a test build (binary executable) that includes the commit, give it a try if you can: https://github.com/FaithLife-Community/test-builds/releases/download/v4.0.0alpha-issue9-20231230-78001b1c/LogosLinuxInstaller

**Comment by savionlee** [comment]
Installer made it all the way through with that patch. No error on file size. @n8marti
